server.port=8081
rabbitmq.queue.order.name=order

# RabbitMQ connection
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin

# Optional (recommended)
spring.rabbitmq.virtual-host=/
spring.rabbitmq.connection-timeout=5000